spring.application.name=knowledge-service

server.port=8085

# MongoDB

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=secureops_knowledge

# Eureka

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Swagger

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html